MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("lifeplan_train",)
  TEST: ("lifeplan_valid",)
SOLVER:
  IMS_PER_BATCH: 2 #8 ### SET TO 4 FOR SWIN-L BASED MODELS (RTX6000)
  BASE_LR: 0.00005
  STEPS: (327778, 355092)

  MAX_ITER: 15000 # CHANGE BASED ON DATASET
  LR_SCHEDULER_NAME: "WarmupCosineLR" # WHEN USING ONE CYCLE POLICY
  WARMUP_ITERS: 4500 # 0.3*TOTAL_ITERS - PyTorch default
  WARMUP_FACTOR: 0.001

  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 512 # ORIGINAL WAS 1024
  MIN_SCALE: 0.5 # original was 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
TEST:
  EVAL_PERIOD: 500 # ORIGINAL WAS 100000
  DETECTIONS_PER_IMAGE: 15 # ORIGINAL WAS 100
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
